# What's this for? This file is used by the markdownlinting extension in VSCode, as well as the GitHub actions
# See all rules at https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Ignore line length
"MD013": false

# Allow multiple headings with the same content provided the headings are not "siblings"
"MD024":
    "siblings_only": true

# We use different page yaml titles to markdown TOC level #1 heading, on purpose, for SEO
"MD025":
    "front_matter_title": ""

# Permit hard tabs in code blocks, since we are likely re-pasting console output
"MD010":
    "code_blocks": false

# Allow trailing punctuation in headings
"MD026": false

# We use fenced code blocks, but this test conflicts with the admonitions plugin we use, which relies 
# on indentation (which is then falsely detected as a code block)
"MD038": false
"MD046": false

# We need inline HTML to embed YouTube videos
"MD033": false